version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    interval: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: pre-commit
    versions:
    - 2.12.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
