language: python
env:
  global:
    - IMAGE_NAME=namelivia/like-and-share-twitter-bot
services:
    - docker
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -e .
before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - python -m unittest discover
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true
    branch: master
    
