language: python
env:
  global:
    - IMAGE_NAME=namelivia/like-and-share-twitter-bot
services:
    - docker
python:
  - 3.7
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - pipenv run pytest --cov-report=xml --cov=like_and_share_twitter_bot tests/
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true
    branch: master
after_sucess:
    - bash <(curl -s https://codecov.io/bash)
